<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<p>${information.name}</p>
<p>${information.birthday}</p>
<p>${information.gender}</p>
<p>${information.national}</p>
<p>${information.idCard}</p>
<p>${information.vehicleMove}</p>
<p>${information.vehicleNumber}</p>
<p>${information.chairNumber}</p>
<p>${information.startDay}</p>
<p>${information.endDay}</p>
<p>${information.movingInformation}</p>
<p>${information.cityName}</p>
<p>${information.districtName}</p>
<p>${information.wardsName}</p>
<p>${information.phone}</p>
<p>${information.email}</p>

<p>${information.fever}</p>
<p>${information.cough}</p>
<p>${information.difficultyOfBreathing}</p>
<p>${information.soreThroat}</p>
<p>${information.vomiting}</p>
<p>${information.skinHemorrhage}</p>
<p>${information.rash}</p>
<p>${information.visitAny}</p>
<p>${information.careFor}</p>
</body>
</html>
